# Generated by Django 5.1.7 on 2025-03-12 04:13

from django.db import migrations

NAME = 0
AGE = 1
EMAIL = 2

RAW_DATA = [
    ["Ajay Kumar Yadav", "31", "aky@g.com"],
    ["Ajay Kumar", "39", "ak@g.com"],
    ["Ajay Yadav", "22", "ay@f.com"],
    ["Kumar Yadav", "24", "ky@e.com"],
    ["Ramesh Yadav", "14", "ry@u.com"],
    ["Ajay Singh", "23", "as@gm.com"]
]

def prefill_candidate_model(apps, schema_editor):
    Candidate = apps.get_model("candidate", "Candidate")
    for data in RAW_DATA:
        Candidate.objects.create(
            name=data[NAME],
            age=data[AGE],
            gender='M',
            email=data[EMAIL],
            phone_number=f'88990088{data[AGE]}'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            prefill_candidate_model,
            reverse_code=migrations.RunPython.noop,
        )
    ]
