# Generated by Django 5.1.7 on 2025-03-20 10:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_add_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='candidate_c_vector__1f94d8_gin'),
        ),
    ]
