# Generated by Django 5.1.7 on 2025-03-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_vector_column_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER vector_column_trigger
                BEFORE INSERT OR UPDATE of name on candidate_candidate
                FOR EACH ROW EXECUTE PROCEDURE
                tsvector_update_trigger(
                    vector_column, 'pg_catalog.english', name
                );

                UPDATE candidate_candidate SET vector_column=null;
            ''',

            reverse_sql='''
                DROP TRIGGER IF EXISTS vector_column_trigger
                ON candidate_candidate;
            '''
        )
    ]
